### ISSUE TITLE
Maps not updating automatically

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/acore-docker#1]
Client data (dbc/maps/vmaps/etc..) is not being updated automatically. When new maps are out, all the current acore-docker setup will fail to execute.

To solve this problem I had to:

- manually delete the client data container
- run `docker-compose pull`
- run `docker-compose up`

This procedure is neither automated nor documented, so most users can't figure it out on their own.

**Comment by FrancescoBorzi** [comment]
@Yehonal if it's not possible to automate this, we should document the manual procedure. What do you say?

**Comment by Yehonal** [comment]
This update procedure should fix the problem: https://github.com/azerothcore/acore-docker#update-your-services-with-latest-images
