### ISSUE TITLE
docker-compose up; ERROR: 'network_mode' and 'networks' cannot be combined

### ISSUE THREAD

**Issue by Telekors** [azerothcore/acore-docker#10]
I believe there is a reconfiguration in docker-compose.yml that causes the following error:

`ERROR: 'network_mode' and 'networks' cannot be combined`

**Comment by Helias** [comment]
what is your docker-compose version? did you try to update it?

**Comment by Telekors** [comment]
Current version is 1.29.2 running on fresh Ubuntu 22.04.01

Interestingly I can get it to start composing if I pull an older version from October it looks like the dev network and dev database might be causing issue the issue for me:
https://github.com/azerothcore/acore-docker/blob/4331e3e73dcc86b3f29534bff6b561403000b006/docker-compose.yml#L204

Do I need the dev-network and dev-database for this to function?

**Comment by Helias** [comment]
try to upgrade your docker-compose to 2.x version.

there was an old issue about it https://github.com/azerothcore/acore-docker/issues/8
moreover, I add into the README to upgrade docker and docker-compose if you encounter a similar issue

**Comment by Telekors** [comment]
That’s definitely it, thanks and sorry totally didn’t think to look at closed issues! :/

**Comment by Helias** [comment]
no worries!
