### ISSUE TITLE
[Issue] Cannot run "ac-db-import" service when change the database password.

### ISSUE THREAD

**Issue by litterlight** [azerothcore/acore-docker#11]
I had changed the database info in .env file after clone the code repository, and then use "docker compose up" command, there shows an error message like below, can anyone help to check? Please comment if I do something wrong, thanks!

My server is Centos
![image](https://user-images.githubusercontent.com/54531564/213387379-f1f0cf75-1092-4466-baa6-1fe6758d5e0e.png)

.env file
![image](https://user-images.githubusercontent.com/54531564/213385985-d6d8d4fd-477e-4e1e-841b-d4c530abee63.png)

error message:
![image](https://user-images.githubusercontent.com/54531564/213386132-7acde5d2-1593-492d-bb49-0d549ba49a10.png)

**Comment by dexterdong** [comment]
试试设置DOCKER_DB_EXTERNAL_PORT

**Comment by ourpurple** [comment]
The same issue is that after modifying the database, ac-db-import cannot be started because it cannot connect to the database

Is there a risk in using the default password for the database, and how should I modify it?

**Comment by squiz-git** [comment]
Having this issue.

**Comment by Helias** [comment]
I do not know if this issue still persists, but we updated a lot the acore-docker so, if it persists, please reopen this issue
