### ISSUE TITLE
ERROR: 'network_mode' and 'networks' cannot be combined

### ISSUE THREAD

**Issue by thestuckster** [azerothcore/acore-docker#17]
Running on Ubuntu with Docker version `20.10.12, build 20.10.12-0ubuntu4`

When I spin up the included docker-compose with `docker-compose up`

I'm met with this error: 
```
ERROR: 'network_mode' and 'networks' cannot be combined
```

**Comment by Helias** [comment]
as suggested here https://github.com/azerothcore/acore-docker/issues/8 and here https://github.com/azerothcore/acore-docker/issues/10, upgrade your docker-compose

I added this suggestion also in the README
