### ISSUE TITLE
service ac-dev-server declares mutually exclusive `network_mode` and `networks`: invalid compose project

### ISSUE THREAD

**Issue by wkchunqiu** [azerothcore/acore-docker#18]
Excuse me for this error What's the problem?

**Comment by Helias** [comment]
I do not know exactly the nature of the issue but as I recommended in several issues and written in the README you can fix this issue upgrading your docker and docker-compose version.

README source:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/519778/235427870-2ac2652f-a8a7-4c07-acf1-bf31de732b34.png">

Users encountered this issue and solved upgrading docker:
https://github.com/azerothcore/acore-docker/issues/8
https://github.com/azerothcore/acore-docker/issues/10
https://github.com/azerothcore/acore-docker/issues/17

Please, check the existing issues before open a new one

**Comment by houbing2006** [comment]
Delete "   network_mode: service:ac-dev-database" in the file "docker compose.yml"

**Comment by Helias** [comment]
I think you are right and I was wrong, probably the new versions ignore this non-working command, we have to comment this to make the docker container works
I think that who wrote that made a mis-match of the name

Fixed, thanks @houbing2006
