### ISSUE TITLE
service ac-dev-server declares mutually exclusive `network_mode` and `networks`: invalid compose project

### ISSUE THREAD

**Issue by wkchunqiu** [azerothcore/acore-docker#19]
service ac-dev-server declares mutually exclusive `network_mode` and `networks`: invalid compose project

**Comment by wkchunqiu** [comment]
May I ask how to solve this problem? Both Windows and Mac have the same error

**Comment by Helias** [comment]
what is your docker-compose and docker version?

**Comment by wkchunqiu** [comment]
Docker Compose version v2.17.3

**Comment by wkchunqiu** [comment]
> what is your docker-compose and docker version?

Docker Compose version v2.17.3

**Comment by wkchunqiu** [comment]
> > what is your docker-compose and docker version?
> 
> Docker Compose version v2.17.3

Docker version 23.0.5, build bc4487a

**Comment by wkchunqiu** [comment]
> > > what is your docker-compose and docker version?
> > 
> > 
> > Docker Compose version v2.17.3
> 
> Docker version 23.0.5, build bc4487a

Docker Desktop 4.19.0

**Comment by Helias** [comment]
what is your docker-compose version?
run `$ docker-compose --version` for it

**Comment by michaeldelago** [comment]
This line should be removed from the file

https://github.com/azerothcore/acore-docker/blob/master/docker-compose.yml#L160

**Comment by Helias** [comment]
should be fixed now thanks
