### ISSUE TITLE
service ac-dev-server declares mutually exclusive `network_mode` and `networks`: invalid compose project

### ISSUE THREAD

**Issue by liuchunyu524** [azerothcore/acore-docker#20]
win11 docker when i run docker compose up,  error occurred

**Comment by Helias** [comment]
? did you upgrade your docker-compose? are you using the last version of acore-docker? if so, what is the HASH of the last commit in your local project?

**Comment by Helias** [comment]
this issue should be solved, if you still encounter this issue with the latest version of acore-docker and upgrading your docker/docker-compose, reopen this issue please
