### ISSUE TITLE
Already connected

### ISSUE THREAD

**Issue by Arispex** [azerothcore/acore-docker#22]
I followed the tutorial to deploy the project on my cloud server. Then I modified the "address" in "realmlist" in MySQL to the IP of the cloud server. However, the client is stuck on the "Server Selection" page and shows the message "Already connected." What should I do?

**Comment by Helias** [comment]
are you using localhost as set realmlist or a local ip?

**Comment by Arispex** [comment]
> are you using localhost as set realmlist or a local ip?

local ip, 127.0.0.1.
