### ISSUE TITLE
how can I export my database about all of the accounts? 

### ISSUE THREAD

**Issue by kuntung** [azerothcore/acore-docker#24]
because the linux server will not available in the future. I have to export these accounts data and import them into another server.
Is there any ways to do this?
many thanks.

**Comment by Helias** [comment]
You could connect to the docker container where there is mysql and export the data content, if you connect a volume to the docker container you could move the exported data into the volume path and get the data outside from the docker container

This help support request is more about docker and mysql, please google a bit to check how to connect into a docker container or how to do a mysql dump
