### ISSUE TITLE
unable to start ac-authserver & ac-worldserver

### ISSUE THREAD

**Issue by alsemo** [azerothcore/acore-docker#28]
Hi,

The acore-docker version is as per the date of this post. I previously have a running acore-docker working fine, aged about a few months back. So yesterday, I updated my installation via the standard "docker compose pull" etc, but unable to start the ac-authserver and ac-worldserver. Thinking that probably the db update was at fault, I decided to do a clean install to test. With the same result. So far these are my findings.

Issues:
1) ac-eluna-ts-dev container prompting "Error: Permission" related issue which after I dig around, I found that that the container are having problem trying to use these folders and files contained in acore-docker/scripts. This includes acore-docker/scripts/lua and acore-docker/typescript.

Solutions: I chown the folder acore-docker/scripts and both it's subfolders lua and typescript with the group id of 1000 . This resolved the "Permission" error I received earlier with now the container are able to create the required files. But now the container is showing as "unhealthy" with the log of:

// ac-eluna-ts-dev log START
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
added 48 packages, and audited 49 packages in 26s
5 packages are looking for funding
  run `npm fund` for details
npm notice 
npm notice New major version of npm available! 8.19.3 -> 10.1.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.1.0>
npm notice Run `npm install -g npm@10.1.0` to update!
npm notice 
found 0 vulnerabilities
> @azerothcore/eluna-ts@1.0.0 dev
> node run build --watch
3:55:51 AM - Starting compilation in watch mode...
3:55:56 AM - Found 0 errors. Watching for file changes.
npm ERR! path /eluna-ts
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh -c -- node run build --watch
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-09-14T03_55_47_349Z-debug-0.log
up to date, audited 49 packages in 2s
5 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
> @azerothcore/eluna-ts@1.0.0 dev
> node run build --watch
4:33:23 AM - Starting compilation in watch mode...
4:33:26 AM - Found 0 errors. Watching for file changes.
//ac-eluna-ts-dev log END

2) ac-db-import unable to run properly. I checked the log and got this:

// ac-db-import log START
DatabasePool Login NOT opened. There were errors opening the MySQL connections. Check your log file for specific errors
qCould not connect to MySQL database at 127.0.0.1: Can't connect to MySQL server on '127.0.0.1:3306' (111)
DatabasePool Login NOT opened. There were errors opening the MySQL connections. Check your log file for specific errors
AzerothCore rev. 27943b6175ca+ 2023-09-13 23:59:51 +0000 (master branch) (Unix, RelWithDebInfo, Static) (dbimport)
<Ctrl-C> to stop.
   █████╗ ███████╗███████╗██████╗  ██████╗ ████████╗██╗  ██╗
  ██╔══██╗╚══███╔╝██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝██║  ██║
  ███████║  ███╔╝ █████╗  ██████╔╝██║   ██║   ██║   ███████║
  ██╔══██║ ███╔╝  ██╔══╝  ██╔══██╗██║   ██║   ██║   ██╔══██║
  ██║  ██║███████╗███████╗██║  ██║╚██████╔╝   ██║   ██║  ██║
  ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
                                 ██████╗ ██████╗ ██████╗ ███████╗
                                ██╔════╝██╔═══██╗██╔══██╗██╔════╝
                                ██║     ██║   ██║██████╔╝█████╗
                                ██║     ██║   ██║██╔══██╗██╔══╝
                                ╚██████╗╚██████╔╝██║  ██║███████╗
                                 ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
     AzerothCore 3.3.5a  -  www.azerothcore.org
> Using configuration file:       /azerothcore/env/dist/etc/dbimport.conf
> Using SSL version:              OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
> Using Boost version:            1.71.0
 
Opening DatabasePool 'acore_auth'. Asynchronous connections: 1, synchronous connections: 1.

// ac-db-import log END

3) ac-client-data exit with status " 0 " when started. No log.

4) ac-authserver and ac-worldserver unable to start, both exited with code " 1 ".

From my surface understanding, this might be related to ac-db-import and ac-eluna-ts-dev issue.

May I know if others have the same problem with the new version?

**Comment by Helias** [comment]
try again with the latest version of acore-docker
