### ISSUE TITLE
Map file '/azerothcore/env/dist/data/maps/0004331.map': does not exist!

### ISSUE THREAD

**Issue by dancheng9999** [azerothcore/acore-docker#29]
docker compose up

and 

acore-docker-ac-worldserver-1   | Map file '/azerothcore/env/dist/data/maps/0004331.map': does not exist!
acore-docker-ac-worldserver-1   | exit code: 1
acore-docker-ac-worldserver-1   | worldserver terminated, restarting...
acore-docker-ac-worldserver-1   | worldserver Terminated after 1 seconds, termination count: : 5
acore-docker-ac-worldserver-1   | Running without GDB
acore-docker-ac-worldserver-1   | Error while configuring Appender GM in Logger commands.gm. Appender does not exist

**Comment by Helias** [comment]
let me know if you encounter the issue now

**Comment by dancheng9999** [comment]
> let me know if you encounter the issue now

thank you very much， it s working
