### ISSUE TITLE
Database does not get populated with client data.

### ISSUE THREAD

**Issue by NicolaiLolansen** [azerothcore/acore-docker#3]
Following this guide: https://www.azerothcore.org/acore-docker/#step-by-step-installation

On the import step, you end up with this error message:

```
redacted:~/acore-docker# docker compose up ac-db-import
[+] Running 3/3
 ⠿ Network acore-docker_default           Created                                                 0.1s
 ⠿ Container acore-docker-ac-database-1   Running                                                 0.0s
 ⠿ Container acore-docker-ac-db-import-1  Created                                                 0.1s
Attaching to acore-docker-ac-db-import-1
acore-docker-ac-db-import-1  | Could not connect to MySQL database at ac-database: Unknown database 'acore_auth'
```

It seems the database is not created in the import script, and so it doesnt get populated. One can go in and do it manually for:

acore_auth

acore_world

acore_characters

```

**Comment by Yehonal** [comment]
Fixed here: https://github.com/azerothcore/acore-docker/commit/5887cad61c72ad97e2d1d398639bc9ab23a7a43a
