### ISSUE TITLE
make: *** [Makefile:130: all] Error 2

### ISSUE THREAD

**Issue by dancheng9999** [azerothcore/acore-docker#31]
cd /wow/

wget https://github.com/ZhengPeiRu21/azerothcore-wotlk/archive/refs/heads/Playerbot.zip

unzip

mv azerothcore-wotlk-Playerbot azerothcore-wotlk

 wget https://github.com/ZhengPeiRu21/mod-playerbots/archive/AzerothCore.zip

unzip

mv mod-playerbots-AzerothCore /wow/azerothcore-wotlk/modules

./acore.sh docker build
...
/usr/bin/ld: ../../../modules/libmodules.a(ModulesLoader.cpp.o): in function `AddModulesScripts()':
/azerothcore/var/build/obj/modules/gen_scriptloader/static/ModulesLoader.cpp:53: undefined reference to `Addmod_playerbots_AzerothCoreScripts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/apps/CMakeFiles/worldserver.dir/build.make:177: src/server/apps/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1086: src/server/apps/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Helias** [comment]
this is probably not related to acore-docker but to mod-playerbots
@ZhengPeiRu21 ?
