### ISSUE TITLE
client can not login game 

### ISSUE THREAD

**Issue by dancheng9999** [azerothcore/acore-docker#32]
account create dc 111111 111111                           

mysql -uroot -ppassword
SHOW DATABASES;
mysql> use acore_auth
SELECT * FROM realmlist;
UPDATE realmlist SET address='192.168.37.128';      

realmlist.wtf
SET realmlist 192.168.37.128                                       

azerothcore-wotlk-ac-worldserver-1  | Load Petitions...
azerothcore-wotlk-ac-worldserver-1  | >> Loaded 0 Petitions!
azerothcore-wotlk-ac-worldserver-1  |  
azerothcore-wotlk-ac-worldserver-1  | Load Petition Signs...
azerothcore-wotlk-ac-worldserver-1  | >> Loaded 0 Petition signs!
azerothcore-wotlk-ac-worldserver-1  |  
azerothcore-wotlk-ac-worldserver-1  | Load Stored Loot Items...
azerothcore-wotlk-ac-worldserver-1  | >> Loaded 0 stored items!
azerothcore-wotlk-ac-worldserver-1  |  
azerothcore-wotlk-ac-worldserver-1  | Load Channel Rights...
azerothcore-wotlk-ac-worldserver-1  | >> Loaded 0 Channel Rights!
azerothcore-wotlk-ac-worldserver-1  |  
azerothcore-wotlk-ac-worldserver-1  | Load Channels...
azerothcore-wotlk-ac-worldserver-1  | >> Loaded 0 channels. DB table `channels` is empty.
azerothcore-wotlk-ac-worldserver-1  |  
azerothcore-wotlk-ac-worldserver-1  | WORLD: World Initialized In 0 Minutes 15 Seconds
azerothcore-wotlk-ac-worldserver-1  |  
azerothcore-wotlk-ac-worldserver-1  | AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, RelWithDebInfo, Static)
azerothcore-wotlk-ac-worldserver-1  | WARNING: You are using OpenSSL version 1.1 which is soon EOL!
azerothcore-wotlk-ac-worldserver-1  | This version will be deprecated. Consider upgrading to OpenSSL 3.0 or 3.1!
azerothcore-wotlk-ac-worldserver-1  | Starting up Auction House Listing thread...
azerothcore-wotlk-ac-worldserver-1  | Calendar deletion of old events.
azerothcore-wotlk-ac-worldserver-1  | AC> Update time diff: 2. Players online: 0.
azerothcore-wotlk-ac-authserver-1   | Ping MySQL to keep connection alive

**Comment by xiaohuzhou** [comment]
if anyone meet this problem again, you need to modify the realmlist.wtf in **/Data/zhCN** or  **/Data/zhTW**,  not only the file in boot directory!
