### ISSUE TITLE
/entrypoint.sh: line 22: /azerothcore/env/dist/bin/dbimport: No such file or directory

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/acore-docker#36]
![image](https://github.com/azerothcore/acore-docker/assets/75517/08dadb91-048e-4442-9cce-8c358b28d051)

**Comment by hkbbdx** [comment]
acore-docker-ac-eluna-ts-dev-1 exited with code 1
acore-docker-ac-eluna-ts-dev-1 exited with code 1
acore-docker-ac-eluna-ts-dev-1 exited with code 1
acore-docker-ac-db-import-1     | '/azerothcore/env/ref/etc/authserver.conf.dist' -> '/azerothcore/env/dist/etc/authserver.conf.dist'
acore-docker-ac-db-import-1     | '/azerothcore/env/ref/etc/dbimport.conf.dist' -> '/azerothcore/env/dist/etc/dbimport.conf.dist'
acore-docker-ac-db-import-1     | '/azerothcore/env/ref/etc/modules' -> '/azerothcore/env/dist/etc/modules'
acore-docker-ac-db-import-1     | '/azerothcore/env/ref/etc/modules/mod_LuaEngine.conf.dist' -> '/azerothcore/env/dist/etc/modules/mod_LuaEngine.conf.dist'
acore-docker-ac-db-import-1     | '/azerothcore/env/ref/etc/worldserver.conf.dist' -> '/azerothcore/env/dist/etc/worldserver.conf.dist'
acore-docker-ac-db-import-1     | '/azerothcore/env/dist/etc/worldserver.conf.dist' -> '/azerothcore/env/dist/etc/worldserver.conf'
acore-docker-ac-db-import-1     | /entrypoint.sh: line 22: /azerothcore/env/dist/bin/dbimport: No such file or directory
acore-docker-ac-db-import-1     | Starting worldserver...
acore-docker-ac-db-import-1 exited with code 127
service "ac-db-import" didn't complete successfully: exit 127

**Comment by darthsyn** [comment]
![image](https://github.com/azerothcore/acore-docker/assets/97857506/beb2e7fa-8b46-4c0c-acef-07a38b3fdb65)


been getting this error with DB import for a week, I fixed the other exit codes you guys are getting by adding my user to the docker group to avoid using sudo

**Comment by zls3434** [comment]
same error

```
$ docker compose up -d && docker compose logs -f
[+] Running 8/8
 ✔ Network acore-docker_default              Created                                                                                                                                  0.1s 
 ✔ Network acore-docker_ac-network           Created                                                                                                                                  0.1s 
 ✔ Container acore-docker-ac-eluna-ts-dev-1  Started                                                                                                                                  0.1s 
 ✔ Container acore-docker-ac-database-1      Healthy                                                                                                                                  0.1s 
 ✔ Container acore-docker-ac-client-data-1   Started                                                                                                                                  0.1s 
 ✘ Container acore-docker-ac-db-import-1     service "ac-db-import" didn't complete successfully: exit 127                                                                            0.0s 
 ✔ Container acore-docker-ac-authserver-1    Created                                                                                                                                  0.0s 
 ✔ Container acore-docker-ac-worldserver-1   Created                                                                                                                                  0.0s 
service "ac-db-import" didn't complete successfully: exit 127
```

```
$ docker logs -f acore-docker-ac-db-import-1
'/azerothcore/env/ref/etc/authserver.conf.dist' -> '/azerothcore/env/dist/etc/authserver.conf.dist'
'/azerothcore/env/ref/etc/dbimport.conf.dist' -> '/azerothcore/env/dist/etc/dbimport.conf.dist'
'/azerothcore/env/ref/etc/modules' -> '/azerothcore/env/dist/etc/modules'
'/azerothcore/env/ref/etc/modules/mod_LuaEngine.conf.dist' -> '/azerothcore/env/dist/etc/modules/mod_LuaEngine.conf.dist'
'/azerothcore/env/ref/etc/worldserver.conf.dist' -> '/azerothcore/env/dist/etc/worldserver.conf.dist'
'/azerothcore/env/dist/etc/worldserver.conf.dist' -> '/azerothcore/env/dist/etc/worldserver.conf'
Starting worldserver...
/entrypoint.sh: line 22: /azerothcore/env/dist/bin/dbimport: No such file or directory
```

**Comment by gr33k** [comment]
I get this too - last time I had to pull a new instance from github and move stuff manually to bring this back up. Can someone please advise how to fix this without all that effort? A quick answer would be greatly appreciated - server is down at the moment :( Thank you much

Update: Even a new git pull runs in to this apparently - Just stuck now it seems.

**Comment by hanskroner** [comment]
Seems to be caused by an unfortunate copy/paste mistake in `docker-compose.yml`
https://github.com/azerothcore/acore-docker/blob/7f9ac16603ef9ecbe3d10df51758543ff649873f/docker-compose.yml#L126

Should that be `image: acore/ac-wotlk-db-import:${DOCKER_IMAGE_TAG:-7.0.0-dev.1}` ?

**Comment by Terrency** [comment]
> Seems to be caused by an unfortunate copy/paste mistake in `docker-compose.yml`
> 
> https://github.com/azerothcore/acore-docker/blob/7f9ac16603ef9ecbe3d10df51758543ff649873f/docker-compose.yml#L126
> 
> Should that be `image: acore/ac-wotlk-db-import:${DOCKER_IMAGE_TAG:-7.0.0-dev.1}` ?
Thank you, it works.

**Comment by Helias** [comment]
this issue is not preset in https://github.com/azerothcore/acore-docker/pull/34
