### ISSUE TITLE
eluna is not work

### ISSUE THREAD

**Issue by GonyJean** [azerothcore/acore-docker#37]
After using acore-docker to start the game, the lua file in script/lua cannot be loaded. 
What is shown in the log is this:
![image](https://github.com/azerothcore/acore-docker/assets/14261751/7f454a99-bd49-4152-913f-9b6d56329f6c)

by the way I use reload enluna and there is a 'reload enluna...' prompt but the lua script is not loaded in the game.

**Comment by Helias** [comment]
please, try again with the latest version, if you still encounter the error open the issue again here and leave a comment
