### ISSUE TITLE
Service "ac-db-import" didn't complete successfully: exit 127

### ISSUE THREAD

**Issue by Nyvek** [azerothcore/acore-docker#38]
~/acore-docker$ sudo docker compose up
[+] Running 8/8
 ✔ Network acore-docker_ac-network           Created                                                                                                                                                 0.1s 
 ✔ Network acore-docker_default              Created                                                                                                                                                 0.1s 
 ✔ Container acore-docker-ac-eluna-ts-dev-1  Created                                                                                                                                                 0.1s 
 ✔ Container acore-docker-ac-database-1      Created                                                                                                                                                 0.1s 
 ✔ Container acore-docker-ac-client-data-1   Created                                                                                                                                                 0.2s 
 ✔ Container acore-docker-ac-db-import-1     Created                                                                                                                                                 0.1s 
 ✔ Container acore-docker-ac-authserver-1    Created                                                                                                                                                 0.1s 
 ✔ Container acore-docker-ac-worldserver-1   Created                                                                                                                                                 0.2s 
Attaching to acore-docker-ac-authserver-1, acore-docker-ac-client-data-1, acore-docker-ac-database-1, acore-docker-ac-db-import-1, acore-docker-ac-eluna-ts-dev-1, acore-docker-ac-worldserver-1
acore-docker-ac-database-1      | 2023-11-07 21:35:35+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.35-1.el8 started.
acore-docker-ac-client-data-1   | #######################
acore-docker-ac-client-data-1   | Client data downloader
acore-docker-ac-client-data-1   | #######################
acore-docker-ac-client-data-1   | Downloading client data in: /azerothcore/env/dist/data/data.zip ...
acore-docker-ac-client-data-1   |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
acore-docker-ac-client-data-1   |                                  Dload  Upload   Total   Spent    Left  Speed
acore-docker-ac-database-1      | 2023-11-07 21:35:35+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
acore-docker-ac-database-1      | 2023-11-07 21:35:35+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.35-1.el8 started.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
acore-docker-ac-database-1      | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
acore-docker-ac-database-1      | 2023-11-07T21:35:36.144187Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
acore-docker-ac-database-1      | 2023-11-07T21:35:36.146598Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.35) starting as process 1
acore-docker-ac-database-1      | 2023-11-07T21:35:36.158469Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
acore-docker-ac-database-1      | 2023-11-07T21:35:36.467802Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
acore-docker-ac-database-1      | 2023-11-07T21:35:36.842846Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
acore-docker-ac-database-1      | 2023-11-07T21:35:36.842932Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
acore-docker-ac-database-1      | 2023-11-07T21:35:36.851622Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
acore-docker-ac-database-1      | 2023-11-07T21:35:36.908446Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
acore-docker-ac-database-1      | 2023-11-07T21:35:36.908542Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.35'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
acore-docker-ac-db-import-1     | '/azerothcore/env/ref/etc/authserver.conf.dist' -> '/azerothcore/env/dist/etc/authserver.conf.dist'
acore-docker-ac-db-import-1     | '/azerothcore/env/ref/etc/dbimport.conf.dist' -> '/azerothcore/env/dist/etc/dbimport.conf.dist'
acore-docker-ac-db-import-1     | '/azerothcore/env/ref/etc/modules' -> '/azerothcore/env/dist/etc/modules'
acore-docker-ac-db-import-1     | '/azerothcore/env/ref/etc/modules/mod_LuaEngine.conf.dist' -> '/azerothcore/env/dist/etc/modules/mod_LuaEngine.conf.dist'
acore-docker-ac-db-import-1     | '/azerothcore/env/ref/etc/worldserver.conf.dist' -> '/azerothcore/env/dist/etc/worldserver.conf.dist'
acore-docker-ac-db-import-1     | '/azerothcore/env/dist/etc/worldserver.conf.dist' -> '/azerothcore/env/dist/etc/worldserver.conf'
acore-docker-ac-db-import-1     | Starting worldserver...
acore-docker-ac-db-import-1     | /entrypoint.sh: line 22: /azerothcore/env/dist/bin/dbimport: No such file or directory
acore-docker-ac-eluna-ts-dev-1  | npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
acore-docker-ac-eluna-ts-dev-1  | 
acore-docker-ac-eluna-ts-dev-1  | added 48 packages, and audited 49 packages in 7s
acore-docker-ac-eluna-ts-dev-1  | 
acore-docker-ac-eluna-ts-dev-1  | 6 packages are looking for funding
acore-docker-ac-eluna-ts-dev-1  |   run `npm fund` for details
acore-docker-ac-eluna-ts-dev-1  | 
acore-docker-ac-eluna-ts-dev-1  | found 0 vulnerabilities
acore-docker-ac-eluna-ts-dev-1  | npm notice 
acore-docker-ac-eluna-ts-dev-1  | npm notice New major version of npm available! 8.19.3 -> 10.2.3
acore-docker-ac-eluna-ts-dev-1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.3>
acore-docker-ac-eluna-ts-dev-1  | npm notice Run `npm install -g npm@10.2.3` to update!
acore-docker-ac-eluna-ts-dev-1  | npm notice 
service "ac-db-import" didn't complete successfully: exit 127

I can't seem to get past this point.

**Comment by gr33k** [comment]
Looks like a dupe of https://github.com/azerothcore/acore-docker/issues/36 - Lots of people are probably experiencing this as I use a vanilla acore-docker and I'm also getting it

**Comment by Helias** [comment]
thanks for report this but I am considering it a duplicate so I am closing this issue

**Comment by ruiserver** [comment]
我也是这个问题，为什么啊？
