### ISSUE TITLE
acore-docker-ac-client-data-1   | curl: (35) error:0A000126:SSL routines::unexpected eof while reading

### ISSUE THREAD

**Issue by Terrency** [azerothcore/acore-docker#39]
when i use docker compose up command, i get the following errors and exited with code 35

acore-docker-ac-client-data-1   | curl: (35) error:0A000126:SSL routines::unexpected eof while reading
acore-docker-ac-client-data-1 exited with code 35
service "ac-client-data" didn't complete successfully: exit 35

**Comment by Helias** [comment]
what is your OS?
what docker version are you using? did you updated it?

**Comment by Terrency** [comment]
my env is Win 11 with docker desktop 4.26.1, latest version
i have tried to compile from azerothcore-wotlk or use prebuild images, but all failed.

ac-client-data-1   | curl: (35) error:0A000126:SSL routines::unexpected eof while reading

I used this project 3 days ago. it works after change db-import image

**Comment by Terrency** [comment]
wordserver with logs:
Can't set process priority class, error: Permission denied
Map file '/azerothcore/env/dist/data/maps/0004331.map': does not exist!
Error while configuring Appender GM in Logger commands.gm. Appender does not exist

**Comment by ddssxx** [comment]
I also have the same question:
ac-client-data-1   | curl: (56) OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0
ac-client-data-1 exited with code 56.
May I ask how this issue was investigated or handled?

**Comment by Helias** [comment]
I didn't investigate it because I was not able to reproduce it.
The issue author closed it, so I think he solved.

From the error I am a bit afraid that your docker container can't download the data from github, maybe there is some connection issue between your docker container and the network itself
