### ISSUE TITLE
[Error] Table 'acore_world.version' doesn't exist, might implies that Database need to update - commit 835cf3a

### ISSUE THREAD

**Issue by t0ury** [azerothcore/acore-docker#43]
Got error in first run of the docker compose, container ac-db-import fail to start up
* [Error] Table 'acore_world.table' doesn't exist 
```
 ERROR 1146 (42S02) at line 2 in file: '/azerothcore/data/sql/updates/db_world/2024_07_16_02.sql': Table 'acore_world.version' doesn't exist
acore-docker-ac-db-import-1     | 
acore-docker-ac-db-import-1     | Applying of file '/azerothcore/data/sql/updates/db_world/2024_07_16_02.sql' to database 'acore_world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
acore-docker-ac-db-import-1     | Could not update the World database, see log for details.
```
by searching documents in *AzerothCore*, the section *Errores comunes* indicate that error was due to database structure is not up to date.

https://www.azerothcore.org/wiki/es/common-errors

**Comment by TheNotary** [comment]
I hit this problem too when testing out the docker compose stuff.  For me, things went sideways because my docker for desktop ran out of space.  The solutions was to increase the space in the app, delete all the containers and images I had `docker system prune`, and then delete the volumes related to the docker compose before trying again:

```
docker compose down --rmi all -v --remove-orphans

docker compose up
```

**Comment by mevacant** [comment]
clean all containers, images, volumns and run "docker compose up" again
notice that you must wait "data image" download  "data.zip" finished
