### ISSUE TITLE
Stuck at Realm Selection List

### ISSUE THREAD

**Issue by wiikid3000** [azerothcore/acore-docker#6]
Just installed acore docker with docker compose. Created user and logged in fine with client but stuck at the realm selection screen. Always loops. Read that it could be the world server not started or it could be an IP issue with a SQL table. I changed the local IP address in the acore_auth realmlist to a local IP but that didn't work either.

**Comment by Helias** [comment]
What did you put as realmlist? I expect something like
`set realmlist localhost`

**Comment by wiikid3000** [comment]
realmlist is sql is set to the default 127.0.0.1 (I tried changing to 192.168.1.111 as thats the same IP as the ubuntu host, but same result). The client is on another PC on the same LAN and realmlist.wtf is `set realmlist 192.168.1.111`

**Comment by wiikid3000** [comment]
I got it, it was a SQL issue where I failed to change the IP address in the "Data" tab. I only updated the IP address in the Tables.
