### ISSUE TITLE
Access worldserver.conf in Docker

### ISSUE THREAD

**Issue by wiikid3000** [azerothcore/acore-docker#7]
I've installed the server and everything is up and running. However, I'd like to make it so the max professions is greater than 2. I've read I need to edit the MaxPrimaryTradeSkill in worldserver.conf. How can I edit the .conf file in Docker? Thanks to all of you for the hard work and nice documentation!

**Comment by Helias** [comment]
You should use:
```
docker exec -it [CONTAINER_ID] bash
```
in this way you can open a terminal session inside the docker container and edit the worldserver.conf.dist or better create a worldserver.conf next to the worldserver.conf.dist to make these changes

moreover, keep in mind that doing this will create a **temporary** change into the docker container, to make it permanent you need to use [docker volumes.](https://docs.docker.com/engine/reference/commandline/volume_create/)

**Comment by Yehonal** [comment]
Why not reading the documentation instead? https://github.com/azerothcore/acore-docker#changing-your-server-configurations 

Seems easier IMHO
