### ISSUE TITLE
ERROR: 'network_mode' and 'networks' cannot be combined

### ISSUE THREAD

**Issue by bolinz** [azerothcore/acore-docker#8]
# OS: 
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar

#  Software:

docker version: 20.10.21
docker-compose version 1.29.2, build unknown

# Step:
1. git clone https://github.com/azerothcore/acore-docker
2. cd acore-docker/
3. docker-compose up

**Comment by Helias** [comment]
did you try to update your docker compose?

**Comment by bolinz** [comment]
> did you try to update your docker compose?

seems the  v2 docker compose only supported. I install v2 compose https://github.com/docker/compose, it works.
