### ISSUE TITLE
Unknown commands for "docker compose down"

### ISSUE THREAD

**Issue by Kuiriel** [azerothcore/acore-docker#9]
### Steps to reproduce the problem

Install via acore-docker guide. Celebrate, enjoy. 
Attempt to remove via docker compose down –rmi all -v –remove-orphans
See unknown command "–remove-orphans" for "docker compose down"

===

Sorry if I've done something stupid and am wasting your time. I followed the ChromieCraft Docker Desktop install guide, which was sourced from https://www.azerothcore.org/acore-docker/

docker compose ps and other instructions for installing and running docker desktop azeroth core functioned without issue.

I wanted to install modules but the folder names don't match module installation instructions for docker desktop, and the bash dashboard instructions don't appear to indicate how to install modules if not using cmake which is in all the module instructions, so I thought I would remove everything and start over with the classic install guide instead.

I got stuck on the removing everything bit, and feel proper daft.

For some reason I seem to be unable to remove the containers to start fresh. There are listed commands for uninstalling and removing the volumes which windows responds with "unknown command"
```
docker compose down –rmi all -v –remove-orphans
docker compose down –remove-orphans
```

results in either

unknown command "–remove-orphans" for "docker compose down"

or 

unknown command "–rmi" for "docker compose down"

### Workaround

In the end I just used the Docker Desktop environment where I could click on the trash can symbol for containers, images and volumes to delete it. Maybe the acore-docker guide needs to be updated with a different command?

Thank you for your contribution to all these wonderful projects.

**Comment by Helias** [comment]
I usually use `docker-compose down` with the dash (`-`), may in this way it works?
I don't know exactly the difference between `docker-compose` and `docker compose` but I think that they can differ
